version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: lab1
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: lab1
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./datacsv:/csvdata  

volumes:
  postgres_data:
